baseURL = "https://arthur8485.github.io/"
languageCode = "zh-tw"
title = "Arthur's Blog" 
theme = "dream"

# copyright = ""

googleAnalytics = "UA-161207717-1"

disqusShortname = ""

enableRobotsTXT = true

[params]
  #background = "black"
  backgroundImage = "/img/background/background.jpg"
  linkColor = "seagreen"
  
  author = "Arthur Lin"
  description = "IT engineer for machine learning"
  avatar = "/img/avatar.jpg"
  motto = "Never too late to learn ! Just keep working"
  


  email = "arthur8485@gmail.com"
  github = "arthur8485"
  telegram = "@binogbot"
  linkedin = "asd"
  codepen = "asd"
  stackoverflow = "asd"

  siteStartYear = 2020

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404Button = true
